Repository sambanova/integrations, pull requests merged in 2025-05, with the labels that each got.

#6 Feature: Add weave integration
  README.md
  weave/README.md
  weave/Weave@SambaNova.ipynb
  weave/requirements.txt
Labels: feature

#7 Improvement: weave typos
  weave/README.md
Labels: improvement

#9 Add lm-evaluation-harness notebook
  README.md
  lm_eval_harness/README.md
  lm_eval_harness/quickstart_eval.ipynb
Labels: feature

#8 Feature: Add mcp example
  README.md
  mcp/mcp_sambanova_examples.ipynb
  mcp/requirements.txt
Labels: feature

#10 feat: llama-stack integration
  README.md
  base-requirements.txt
  llama_stack/README.md
  llama_stack/notebooks/01_Quickstart.ipynb
  llama_stack/notebooks/02_Image_Chat.ipynb
  llama_stack/notebooks/03_Tool_Calling.ipynb
  llama_stack/notebooks/04_Rag_Agent.ipynb
  llama_stack/notebooks/05_Safety.ipynb
  llama_stack/requirements.txt
  llama_stack/tests/llama_stack_test.py
  mypy.ini
Labels: documentation, feature

#13 Update continue integration change config from json to yaml
  continue/README.md
  continue/config.json
  continue/config.yaml
Labels: documentation, improvement
